version: "3.2"

services:
  ftp:
    image: hauptmedia/proftpd
    ports:
      - "21:21"
      - "20:20"
    environment:
      - FTP_USERNAME=camel
      - FTP_PASSWORD=pass
    volumes:
      - type: bind
        source: /home/boyscout/projects/veille/camel_in_action/src/main/java/com/example/camel_in_action/chapter2/ftptojms/data/test.txt
        target: /orders/test.txt
      - type: bind
        source: /home/boyscout/projects/veille/camel_in_action/src/main/java/com/example/camel_in_action/chapter2/ftptojms/proftpd.conf
        target: /etc/proftpd/proftpd.conf
      #- /src/main/java/com/example/camel_in_action/chapter2/test.txt:/orders
      #- /src/main/java/com/example/camel_in_action/chapter2/proftpd.conf:/etc/proftpd/proftpd.conf
  activemq:
    image: rmohr/activemq:5.10.0
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161" # web    http://boot2docker:8161/admin (admin:admin)